### ISSUE TITLE
All content disappears after navigation

### ISSUE THREAD

**Issue by dmitriypetrukk** [microspaze/CarouselView.Maui#5]
Hi! I have a carousel view with multiple content views. If I go to the next page, and then go back to the carousel view, all the content disappears and I get an error when I scroll.

<img width="251" alt="image" src="https://github.com/microspaze/CarouselView.Maui/assets/73065241/68fe2778-4947-40ad-a34c-d1071f8310c4">

`System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'Microsoft.Maui.Platform.MauiScrollView'.
  at ObjCRuntime.ThrowHelper.ThrowObjectDisposedException(Object o) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/ObjCRuntime/ThrowHelper.cs:52
  at Foundation.NSObject.get_SuperHandle() in /Users/builder/azdo/_work/1/s/xamarin-macios/src/Foundation/NSObject2.cs:615
  at UIKit.UIScrollView.set_ContentSize(CGSize value) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/build/dotnet/ios/generated-sources/UIKit/UIScrollView.g.cs:602
  at at Microsoft.Maui.Handlers.ScrollViewHandler.SetContentSizeForOrientation(UIScrollView uiScrollView, Double viewportWidth, Double viewportHeight, ScrollOrientation orientation, Size contentSize)
  at at Microsoft.Maui.Handlers.ScrollViewHandler.GetDesiredSize(Double widthConstraint, Double heightConstraint)
  at at Microsoft.Maui.Layouts.LayoutExtensions.ComputeDesiredSize(IView view, Double widthConstraint, Double heightConstraint)
  at at Microsoft.Maui.Controls.ScrollView.MeasureOverride(Double widthConstraint, Double heightConstraint)
  at at Microsoft.Maui.Controls.Compatibility.Layout.Microsoft.Maui.IView.Measure(Double widthConstraint, Double heightConstraint)
  at at Microsoft.Maui.Layouts.LayoutExtensions.MeasureContent(IContentView contentView, Thickness inset, Double widthConstraint, Double heightConstraint)
  at at Microsoft.Maui.Layouts.LayoutExtensions.MeasureContent(IContentView contentView, Double widthConstraint, Double heightConstraint)
  at at Microsoft.Maui.Controls.TemplatedView.Microsoft.Maui.ICrossPlatformLayout.CrossPlatformMeasure(Double widthConstraint, Double heightConstraint)
  at at Microsoft.Maui.Platform.MauiView.CrossPlatformMeasure(Double widthConstraint, Double heightConstraint)
  at at Microsoft.Maui.Platform.MauiView.LayoutSubviews()
  at at Microsoft.Maui.Platform.ContentView.LayoutSubviews()
  at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:58
  at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass) in /Users/builder/azdo/_work/1/s/xamarin-macios/src/UIKit/UIApplication.cs:94
  at Planiversity.Program.Main(String[] args) in /Users/noname/Documents/GitHub/Planiversity-Mobile/PlaniversityMaui/Platforms/iOS/Program.cs:18
`

**Comment by microspaze** [comment]
I will check this issue today. Thanks for reporting!

**Comment by microspaze** [comment]
@dmitriypetrukk  I still can not reproduce your problem. Can you upload a little demo project? Like https://github.com/microspaze/CarouselView.Maui/files/13649047/NullPointerCrashDemo.zip
